### ISSUE TITLE
Documentation - Schema Registry advice

### ISSUE THREAD

**Issue by davydog187** [cogini/avro_schema#1]
Hello and thank you for your great project! `AvroSchema` is a really solid Elixir client for Avro.

Before submitting a PR, I wanted to check to make sure I wasn't missing something.

For both the publisher section and `register_schema/2`, the advice is

> The subject is normally the full name from the Avro schema, though you can register things in the Schema Registry under arbitrary names.

I believe that this is misguided as there are 3 different types of naming strategies as listed in the [Confluent Schema Registry docs](https://docs.confluent.io/current/schema-registry/serializer-formatter.html#subject-name-strategy) 

> Subject Name Strategies
>
> TopicNameStrategy (io.confluent.kafka.serializers.subject.TopicNameStrategy) – this is the default
> RecordNameStrategy (io.confluent.kafka.serializers.subject.RecordNameStrategy)
> TopicRecordNameStrategy (io.confluent.kafka.serializers.subject.TopicRecordNameStrategy)

As noted, `TopicNameStrategy` is the default supported strategy from Confluent. I'm not sure if you had something else in mind, but I wanted to update the documentation to reflect this. Please let me know if I'm missing something, otherwise, I will send a PR.

**Comment by reachfh** [comment]
I am happy to be compatible with Confluent, so your updates sound good.
My own use is mainly with multiple topics carrying the same records, but only one record type per topic. And a major motivation for using the registry is migrating from distributing schemas with the app, so we are "schema centric".
