### ISSUE TITLE
Add Avro.Schema.encode!/2 and replace encode/2 with one that returns success types

### ISSUE THREAD

**Issue by davydog187** [cogini/avro_schema#2]
After using `AvroSchema` for a bit, I'd really like to have an API that catches any encoding errors and returns them in an `:error` tuple.

```elixir
# This is changed
@spec encode(map | [{binary, term}], fun) :: {:ok, binary()} | {:error, String.t()}

# This is effectively the existing funciton
 @spec encode!(map | [{binary, term}], fun) :: binary
```

This would be a breaking change to the API, but would provide a lot of value to consumers who want to choose how they handle encoding errors. I am working on a pull request now for this change. Thanks!

**Comment by reachfh** [comment]
Fine with me.
