### ISSUE TITLE
make_subject assumes a naming strategy

### ISSUE THREAD

**Issue by davydog187** [cogini/avro_schema#23]
make_subject/1 and make_subject/2 assume a particular naming strategy. Sticking with the Confluent [Subject Name Strategy](https://docs.confluent.io/current/schema-registry/serializer-formatter.html#subject-name-strategy) we should probably apply the subject name by a provided strategy.

I'm also not sure what format the current implementation is adhering to?

**Comment by reachfh** [comment]
It's coming from https://github.com/klarna/avlizer, more or less. Their version uses a raw fingerprint, where we are hex encoding it. 
I don't think it's super useful. Maybe with a less generic name.

**Comment by reachfh** [comment]
Commented out these functions.
