### ISSUE TITLE
Schema changes not being registered to Schema Registry

### ISSUE THREAD

**Issue by erikjmiller** [cogini/avro_schema#28]
Hi All, I've been using this and confluent_schema_registry for a while now and I've noticed when I update a schema file, and try to register it to the registry it isn't actually updated locally.  

It seems like the data is getting cached in ets even after I have changed the cache.  I have persistence set to false by setting the cache_dir: nil.

I have managed to get some changes to take effect but it doesn't seem to have any logical method of when it works and when it doesn't.

I'm wondering if I'm using this and the confluent_schema_registry project incorrectly.  

My ideal scenario is when starting the application, via iex, mix, or a production release the current schemas which are stored in "/priv/schemas/" gets registered to the confluent registry.  I don't expect any changes once the application is started, but between starts I would like an initial registration of each schema to handle changes.

Here is the applicable code I'm using...

    @timeslot_schema File.read!("priv/schemas/timeslot.avsc")
    @program_schema File.read!("priv/schemas/program.avsc")
    @tmsprogram_schema File.read!("priv/schemas/tmsprogram.avsc")
    @person_schema File.read!("priv/schemas/person.avsc")
    @avro_schema_opts [cache_dir: nil,
      client: [base_url: Application.get_env(:cae_elastic_load, :schema_registry_url)]]
  
    def register_schemas() do
      {:ok, timeslot_schema_id} = AvroSchema.register_schema("com.gracenote.video.cae.Timeslot", @timeslot_schema)
      {:ok, program_schema_id} = AvroSchema.register_schema("com.gracenote.video.cae.Program", @program_schema)
      {:ok, tmsprogram_schema_id} = AvroSchema.register_schema("com.gracenote.video.cae.Tmsprogram", @tmsprogram_schema)
      {:ok, person_schema_id} = AvroSchema.register_schema("com.gracenote.video.cae.Person", @person_schema)
      %{
        timeslot_schema_id: timeslot_schema_id,
        program_schema_id: program_schema_id,
        tmsprogram_schema_id: tmsprogram_schema_id,
        person_schema_id: person_schema_id
      }
    end

**Comment by reachfh** [comment]
Thanks for the report, I will have a look in the next day or so.

**Comment by erikjmiller** [comment]
I figured out the issue.  Since I'm storing the schemas in module variables, they only get refreshed from compilation of the file.  I've changed the code to have only the file path in the module variables and read the file when register_schemas is called.
