### ISSUE TITLE
Decode map types as maps instead of keyword lists

### ISSUE THREAD

**Issue by davydog187** [cogini/avro_schema#5]
Erlavro decodes Map types as keyword lists. `AvroSchema` can provide a decoder hook for automatically translating them to maps as they are being decoded.

**Comment by reachfh** [comment]
There is a decoder option to specify that, and we can make it the default.
https://github.com/klarna/erlavro/blob/master/src/avro.erl#L256

**Comment by reachfh** [comment]
I added `map_type: :maps` to the default options.
Does that handle it?

**Comment by davydog187** [comment]
I will add a test to validate

**Comment by davydog187** [comment]
I am reverting your change in #10 for now as it breaks the tests
